namespace WildRune.DTOs.LOL
{
    public enum AbilityResource
    {
        MANA, ENERGY, NONE, SHIELD, BATTLEFURY, DRAGONFURY, RAGE, HEAT, GNARFURY, FEROCITY, BLOODWELL, WIND, AMMO, MOONLIGHT, OTHER, MAX
    }
}
